"""daily_reports.suggestion 추가

보호자가 오늘 해볼 만한 것 한 줄. Claude 가 요약과 함께 써 준다.
키가 없거나 호출이 실패하면 비어 있다 — 앱은 그때 이 칸을 감춘다.


Revision ID: deeccd9ed0d3
Revises: 336c3a52f613
Create Date: 2026-08-30 01:30:10.791478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'deeccd9ed0d3'
down_revision: Union[str, Sequence[str], None] = '336c3a52f613'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_reports', sa.Column('suggestion', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_reports', 'suggestion')
    # ### end Alembic commands ###
